#ifndef CONFIG_H
#define CONFIG_H

#define USYNTH_VOICES 2
#define PPG_OSC_BANK_SIZE USYNTH_VOICES
#define USYNTH_EG_BANK_SIZE USYNTH_VOICES
#define USYNTH_LFO_BANK_SIZE USYNTH_VOICES
#define MIDI_VOICES USYNTH_VOICES

#endif